server:
  port: 4060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: skdata
    password: skdata
    url: jdbc:mysql://192.168.70.237:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  elasticjob:
    zookeeper:
      server-lists: 192.168.70.237:2180
      namespace: pig-daemon